apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.kong.environment | nindent 2 }}
  kong.yml:
  {{- toYaml .Values.kong.config | nindent 4 }}
