# General configuration
global:
#   smtp:
#     host:
#     port:
#     user:
#     pass:
#     senderName:
#   siteUrl:

# Per service configuration
# In most cases you can use the 'General configuration' and the the rest AS IS.

# Auth
# my-release-auth
# my-release-kong
# my-release-meta
# my-release-realtime
# my-release-storage
# my-release-rest


# Postgres Database
# A standalone Postgres database configured to work with Supabase services.
database:
  postgresqlPassword: AZERTYUIOP
  initdbScriptsConfigMap: my-release-initdb

studio:
  environment:
    SUPABASE_URL: http://api.localhost
    STUDIO_PG_META_URL: http://my-release-supabase-kong.test-supabase.svc.cluster.local:8000/pg
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE"
    SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U"

  ingress:
    enabled: 'true'
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: studio.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 3000

# Auth Service
auth:
  environment:
    GOTRUE_DB_DATABASE_URL: postgres://postgres:AZERTYUIOP@my-release-database.test-supabase.svc.cluster.local:5432/postgres?search_path=auth
    GOTRUE_SITE_URL: http://studio.localhost
    GOTRUE_URI_ALLOW_LIST: ""
    GOTRUE_DISABLE_SIGNUP: "false"
    GOTRUE_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
    GOTRUE_JWT_EXP: "3600"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "admin@example.com"
    GOTRUE_SMTP_HOST: "mail"
    GOTRUE_SMTP_PORT: "2500"
    GOTRUE_SMTP_USER: "fake_mail_user"
    GOTRUE_SMTP_PASS: "fake_mail_password"
    GOTRUE_SMTP_SENDER_NAME: "fake_sender"
    GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
    GOTRUE_SMS_AUTOCONFIRM: "false"

rest:
  environment:
    PGRST_DB_URI: postgres://postgres:AZERTYUIOP@my-release-database.test-supabase.svc.cluster.local:5432/postgres
    PGRST_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"

realtime:
  environment:
    DB_HOST: my-release-database.test-supabase.svc.cluster.local
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: AZERTYUIOP
    DB_SSL: "false"
    JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"

meta:
  environment:
    PG_META_DB_HOST: my-release-database.test-supabase.svc.cluster.local
    PG_META_DB_PASSWORD: AZERTYUIOP

storage:
  environment:
    ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE"
    SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U"
    POSTGREST_URL: http://my-release-supabase-rest.test-supabase.svc.cluster.local:3000
    PGRST_JWT_SECRET: "your-super-secret-jwt-token-with-at-least-32-characters-long"
    DATABASE_URL: postgres://postgres:AZERTYUIOP@my-release-database.test-supabase.svc.cluster.local:5432/postgres
    PGOPTIONS: -c search_path=storage,public

kong:
  ingress:
    enabled: 'true'
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: api.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 80

  config: |
    _format_version: "1.1"

    ###
    ### Consumers / Users
    ###
    consumers:
      - username: anon
        keyauth_credentials:
          - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE
      - username: service_role
        keyauth_credentials:
          - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U

    ###
    ### Access Control List
    ###
    acls:
      - consumer: anon
        group: anon
      - consumer: service_role
        group: admin

    ###
    ### API Routes
    ###
    services:
      ## Open Auth routes
      - name: auth-v1-open
        url: http://my-release-supabase-auth.test-supabase.svc.cluster.local:9999/verify
        routes:
          - name: auth-v1-open
            strip_path: true
            paths:
              - /auth/v1/verify
        plugins:
          - name: cors
      - name: auth-v1-open-callback
        url: http://my-release-supabase-auth.test-supabase.svc.cluster.local:9999/callback
        routes:
          - name: auth-v1-open-callback
            strip_path: true
            paths:
              - /auth/v1/callback
        plugins:
          - name: cors
      - name: auth-v1-open-authorize
        url: http://my-release-supabase-auth.test-supabase.svc.cluster.local:9999/authorize
        routes:
          - name: auth-v1-open-authorize
            strip_path: true
            paths:
              - /auth/v1/authorize
        plugins:
          - name: cors

      ## Secure Auth routes
      - name: auth-v1
        _comment: "GoTrue: /auth/v1/* -> http://my-release-supabase-auth.test-supabase.svc.cluster.local:9999/*"
        url: http://my-release-supabase-auth.test-supabase.svc.cluster.local:9999/
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Secure REST routes
      - name: rest-v1
        _comment: "PostgREST: /rest/v1/* -> http://my-release-supabase-rest.test-supabase.svc.cluster.local:3000/*"
        url: http://my-release-supabase-rest.test-supabase.svc.cluster.local:3000/
        routes:
          - name: rest-v1-all
            strip_path: true
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Secure Realtime routes
      - name: realtime-v1
        _comment: "Realtime: /realtime/v1/* -> ws://my-release-supabase-realtime.test-supabase.svc.cluster.local:4000/socket/*"
        url: http://my-release-supabase-realtime.test-supabase.svc.cluster.local:4000/socket/
        routes:
          - name: realtime-v1-all
            strip_path: true
            paths:
              - /realtime/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      ## Storage routes: the storage server manages its own auth
      - name: storage-v1
        _comment: "Storage: /storage/v1/* -> http://my-release-supabase-storage.test-supabase.svc.cluster.local:5000/*"
        url: http://my-release-supabase-storage.test-supabase.svc.cluster.local:5000/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors

      ## Secure Database routes
      - name: meta
        _comment: "pg-meta: /pg/* -> http://my-release-supabase-meta.test-supabase.svc.cluster.local:8080/*"
        url: http://my-release-supabase-meta.test-supabase.svc.cluster.local:8080/
        routes:
          - name: meta-all
            strip_path: true
            paths:
              - /pg/
        plugins:
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
